# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70865bd9e3d18c683b543e27e914fce2e98a9c09257bea87bb8ee5559857fb8c257dd88e0878fbf02c4c5152aa66046bb0fce9a1d3c3bb1c6066bcedf3b185b

test:
  secret_key_base: 52f4e3d74e6211f95f9a1049495038726cccb48053962ff4cf347eb936d7ac07583b366cd02bf12b2dba9574ca0c32d15869b44e712d78e2f0339bd1bccc3fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
